---
  #############################################################################
  ## CREST settings
  #############################################################################
  crest:
    # login server URL, uncomment the one you want
    # login_url: "https://sisilogin.testeveonline.com"  # singularity
    # login_url: "https://login.eveonline.com"          # tranquility

    # CREST server URL
    # crest_url: "https://api-sisi.testeveonline.com/"  # singularity
    # crest_url: "https://crest-tq.eveonline.com/"      # tranquility

    # Your app settings from https://developers.eveonline.com/ or https://developers.testeveonline.com/
    clientID: "f"
    secretKey: "4"
    redirectUrl: "http://localhost:4567/callback"